let versions=[],active=0,mode="chapter";const nav=document.querySelector("#nav"),reader=document.querySelector("#reader"),rail=document.querySelector("#rail");
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const slug=s=>s.toLowerCase().startsWith("unreleased")?"unreleased":s.toLowerCase().startsWith("current")?"current":"previous";
const updateSearch=`updating install download pro plan library toolbar font defaults import settings plan layout z.sys-ProPlan trash CALIBZ beta`;
function steps(items){return `<ol class="steps">${items.map(x=>`<li>${x}</li>`).join("")}</ol>`}
function updateChapter(){return `<article class="chapter update-chapter" id="updating"><div class="kicker">START HERE &middot; DOWNLOAD AND UPDATE INSTRUCTIONS</div><h1>How to Update PPX18</h1><p class="deck">Use this chapter when a new version appears in the list on the left side of this page. Each version tells you exactly which PPX18 files were changed: the Pro Plan, Library, Toolbars, Font Files, or another file named in that version's notes.</p><div class="notice"><strong>Start by selecting the version you want from the list on the left.</strong><p>Under the version number, the line beginning with <strong>UPDATED:</strong> names the files you must download and replace. You only need to update the files named on that line.</p></div><div class="accordion-stack">
<details open><summary><span>01</span><div><strong>How to update the Pro Plan file</strong><small>Find the live download link, match the version number, and open the newest Pro Plan</small></div></summary><div class="detail-body"><h3>Where to get the newest PPX18 files</h3><p>Your original PPX18 delivery PDF contains a clickable link to the live Dropbox download folder for your product. That link does not expire when a new PPX18 version is released. Return to the same link to download the newest Pro Plan, Library, Toolbars, Font Files, or other files named in this changelog.</p><p>If you no longer have the delivery PDF handy, open the original PPX18 download saved on your computer and go to the <strong>Step 5</strong> folder. The product link in that folder takes you back to the same live Dropbox download folder.</p><p>If you have neither the PDF nor the Step 5 folder, sign in to your account at <a href="https://rabbitdesign.net" target="_blank" rel="noreferrer"><strong>rabbitdesign.net</strong></a> and download your PPX18 delivery PDF again. Open the PDF and select its Dropbox download link.</p><div class="release-check"><strong>How to confirm that you found the correct file</strong><p>Files in the live Dropbox folder display version numbers. Match the number on the downloaded file to the version number shown in the list on the left. Select that version in the changelog to see everything changed in that release and exactly which files must be replaced.</p></div>${steps([
  `Select the version you are installing from the list on the left side of this page.`,
  `Read the <strong>UPDATED:</strong> line directly below that version number.`,
  `Open the live Dropbox folder using the link in your delivery PDF or the product link in the Step 5 folder.`,
  `Download the newest <strong>Pro Plan</strong> when Pro Plan appears on the UPDATED line. Confirm that its file version matches the changelog version you selected.`,
  `Open and begin working in the newly downloaded Pro Plan. It contains the current PPX18 defaults, macros, labels, custom fields, Saved Plan Views, layer behavior, and coordinated systems.`
])}<p class="tip"><strong>Most users should stop here.</strong> Do not import default settings from an older Pro Plan as part of a normal update. Experienced users who understand Chief Architect default importing may read the final advanced section at the bottom of this chapter.</p></div></details>
<details><summary><span>02</span><div><strong>How to update or replace the PPX18 library in X18 Beta</strong><small>Remove the installed PPX18 library items, empty the Library Trash, and open the newly downloaded library file</small></div></summary><div class="detail-body"><p>Use these steps when the selected version on the left says <strong>Library</strong> after <strong>UPDATED:</strong>. The updated library file is in the same Dropbox download folder linked from your original delivery PDF or from the product links in the Step 5 folder.</p>${steps([
  `Open the Library Browser and select the tag named <strong>z.sys-ProPlan</strong>.`,
  `Inside the Library Browser, open the filtered-results window for the <strong>z.sys-ProPlan</strong> tag. The items shown in that window are the results produced by selecting that tag.`,
  `Select every item shown in the filtered-results window, then press the <strong>Delete</strong> key. You do not need to right-click the selected items.`,
  `Wait for Chief Architect to respond. In the current X18 beta, deleting these items can take a long and unpredictable amount of time. The delay does not appear to correspond to computer speed, and the same computer may complete it quickly one time and slowly another time. Do not continue until deletion finishes.`,
  `Open the Trash library, right-click it, and choose <strong>Empty Trash</strong>. This prevents deleted objects from being detected as duplicates during the next installation.`,
  `After the Library Trash is empty, return to the PPX18 Dropbox download folder and open the newly downloaded <strong>CALIBZ</strong> library file. Allow Chief Architect X18 to finish importing it.`
])}<p class="tip"><strong>Important:</strong> The "newly downloaded library" means the current CALIBZ file from the original PPX18 Dropbox download link. Delete the old tagged library items and empty the Library Trash before opening that updated file.</p></div></details>
<details><summary><span>03</span><div><strong>Import toolbar configurations</strong><small>Use the same procedure documented in the PPX18 manual</small></div></summary><div class="detail-body">${steps([
  `Right-click a blank area of the toolbars and choose <strong>Customize Toolbars</strong>. You can also open <strong>Tools &gt; Toolbars and Hotkeys &gt; Customize Toolbars</strong>.`,
  `Open the <strong>Configurations</strong> panel and select <strong>Import</strong>.`,
  `Browse to the downloaded Toolbars folder and select every TOOLBAR file in that folder.`,
  `Choose <strong>Replace All</strong> to replace the previous PPX18 configurations.`,
  `If Chief Architect displays <strong>Importing Place Library Object Buttons</strong>, allow the process to finish.`,
  `If a selection dialog appears, choose <strong>Select All New</strong>, then press <strong>Done</strong>.`
])}<p class="tip">Save or back up any personal toolbar configuration first. Importing the Rabbitt Design configuration can overwrite toolbar positions, added buttons, and other customizations.</p></div></details>
<details class="advanced-import"><summary><span>04</span><div><strong>Advanced: importing selected settings from an older Pro Plan</strong><small>For experienced users only — this is not part of the normal PPX18 update process</small></div></summary><div class="detail-body"><div class="advanced-warning"><strong>Do not use this section unless you are already comfortable importing Chief Architect defaults.</strong><p>Incorrectly importing defaults can overwrite current PPX18 systems and create problems that require technical support. Most users should use the newly downloaded Pro Plan exactly as supplied and manually re-enter personal preferences when necessary.</p></div><p>This optional process is only for an experienced user who previously customized an older Pro Plan and understands how to select individual import categories. Its purpose is to save time by bringing forward a small number of preferred settings that the newer release did not change.</p><p><strong>Before importing anything, select the destination version from the list on the left and read every release note.</strong> If any release between your old version and the destination version changed a setting, keep the setting supplied by the new Pro Plan.</p>${steps([
  `Make a backup copy of your older customized Pro Plan. The older file is the <strong>source</strong>; the newly downloaded Pro Plan is the <strong>destination</strong>.`,
  `Open the newly downloaded destination Pro Plan. Choose <strong>File &gt; Import &gt; Import Settings From Plan/Layout</strong>, then select the older customized Pro Plan as the source.`,
  `Import only individual setting categories you understand and have confirmed were not changed in any intervening release. Never use this as permission to import all defaults.`,
  `When importing Saved Plan Views or layer sets, leave <strong>Replace Originals</strong> turned off so the PPX18 originals remain intact.`,
  `Inspect and test every imported setting before using the plan for production work.`
])}<a class="image-link" href="images/import-plan-layout-settings.png?v=2" target="_blank" rel="noreferrer"><img class="menu-shot" src="images/import-plan-layout-settings.png?v=2" alt="Complete Chief Architect File menu showing Import Settings From Plan/Layout"></a><p class="image-note">File &gt; Import &gt; Import Settings From Plan/Layout. Select the image to open the complete original screenshot.</p><h3>Defaults that should generally not be imported</h3><ul><li>Do not broadly import wall or framing defaults. PPX18 relies heavily on version-sensitive layer-based fill styles in framing members and wall types.</li><li>Do not import complete default sets.</li><li>Avoid older window and door labels, room labels, room types, base and full-height cabinet defaults, and door defaults.</li><li>Import Project Information fields only when no release between the two versions changed that field or the way it reports.</li></ul><h3>Safer method for a customized object</h3><p>Save the customized object to your user library, place it in the new Pro Plan, run the <strong>Pro Plan Transfer</strong> tool, and then set that updated object as the default. This retains the customization while applying the current PPX18 custom fields, label macros, and label offsets.</p></div></details></div></article>`}
function compareChapter(){return `<article class="chapter compare-chapter" id="compare"><div class="kicker">PPX18 UPDATE HISTORY &middot; MULTI-VERSION COMPARISON</div><h1>Compare PPX18 Versions</h1><p class="deck">Use this chapter when you have skipped one or more updates. It combines every release between the version you currently have and the version you want to install.</p><div class="notice"><strong>Choose your installed version and your destination version.</strong><p>The results will show every intervening release, all accumulated changes, and every Pro Plan, Library, Toolbars, Font Files, or other file you need to download.</p></div><div class="compare-controls"><label>Version currently installed<select id="compare-from"></select></label><label>Version you want to install<select id="compare-to"></select></label><button type="button" id="run-compare">Compare versions</button></div><div id="compare-results" class="compare-results"><p>Select two versions, then choose <strong>Compare versions</strong>.</p></div></article>`}
function explainMigration(item){const text=item.toLowerCase();if(text.includes("floor and ceiling"))return `<strong>Floor and ceiling platform defaults.</strong> If you previously customized platform structure, thickness, materials, or related floor defaults, you may be able to import those specific defaults instead of rebuilding them. Do this only when this release does not list a change to floor or ceiling platforms.`;if(text.includes("saved plan views"))return `<strong>Saved Plan Views.</strong> These may preserve view preferences you already organized. Import them as additional views and leave <em>Replace Originals</em> turned off so the new PPX18 views remain intact.`;if(text.includes("layer sets"))return `<strong>Layer sets.</strong> You may import your personal layer-set variations as new items. Do not replace the layer sets supplied by the new PPX18 release.`;if(text.includes("project-information")||text.includes("project information"))return `<strong>Unchanged Project Information fields.</strong> A field may be brought forward only when this release did not change that field or the way it reports. Compare the release notes before selecting it.`;return `<strong>${esc(item)}.</strong> Treat this as a possible time-saving candidate, not automatic permission to import it. Confirm that the current release did not change the same setting.`}
function explainAvoid(item){const text=item.toLowerCase();if(text.includes("framing")||text.includes("wall"))return `<strong>Framing and wall defaults.</strong> Do not import these from the older plan. PPX18 uses layer-based fill styles and coordinated wall behavior that can be damaged by older defaults.`;if(text.includes("window")||text.includes("door")||text.includes("room")||text.includes("cabinet"))return `<strong>Labels, room systems, doors, windows, and cabinet defaults.</strong> Keep the new PPX18 versions of these items whenever they are listed as changed. For a custom object, use the library plus Pro Plan Transfer method explained in the update chapter.`;if(text.includes("layout")||text.includes("project-information"))return `<strong>Updated layouts and their Project Information fields.</strong> Do not replace the new originals or import an older field that this release changed, because layout labels and reporting may no longer coordinate correctly.`;return `<strong>${esc(item)}.</strong> Keep the setting supplied by the new Pro Plan because this release may depend on its current configuration.`}
function releaseGuide(v){return `<aside class="guide"><section class="card download-card"><h2>Files updated in this version</h2><p>Download each file listed below from the live PPX18 Dropbox folder. These are the exact files changed in this version.</p><ul class="downloads">${v.downloads.map(x=>`<li>${esc(x)}</li>`).join("")}</ul><button class="update-guide-link" type="button" data-update-guide>Open the update instructions &rarr;</button></section></aside>`}
function releaseVisuals(v){if(v.version!=="PPX18 260720")return "";const area=window.PPX_IMAGES?.area||"images/area-analysis-breakdown.png",time=window.PPX_IMAGES?.time||"images/time-tracker-toolbar.png";return `<section class="release-visuals"><h2>PPX18 260720 Feature Examples</h2><figure><a href="${area}" target="_blank" rel="noreferrer"><img src="${area}" alt="Area Analysis Breakdown showing floor-by-floor conditioned area, unconditioned area, coverage, percentage of coverage, and floor area ratio"></a><figcaption><strong>Area Analysis Breakdown</strong> — Find this tool in the <strong>Area Analysis Tools</strong> folder. Unblock the CAD block to display the expanded breakdown for troubleshooting totals and reviewing general area-analysis information.</figcaption></figure><figure><a href="${time}" target="_blank" rel="noreferrer"><img src="${time}" alt="Chief Architect Toolbars menu with Time Logging highlighted"></a><figcaption><strong>Turn on the Time Tracker toolbar</strong> — Right-click a blank space in the toolbar area, open <strong>Toolbars</strong>, and toggle <strong>Time Logging</strong> on.</figcaption></figure></section>`}
function releaseVisualsFixed(v){if(v.version!=="PPX18 260720")return "";const area=window.PPX_IMAGES?.area||"images/area-analysis-breakdown.png",time=window.PPX_IMAGES?.time||"images/time-tracker-toolbar.png";return `<section class="release-visuals"><h2>PPX18 260720 Feature Examples</h2><figure><a href="${area}" target="_blank" rel="noreferrer"><img src="${area}" alt="Area Analysis Breakdown showing floor-by-floor conditioned area, unconditioned area, coverage, percentage of coverage, and floor area ratio"></a><figcaption><h3>Area Analysis Breakdown</h3><p>Find this tool in the <strong>Area Analysis Tools</strong> folder. Unblock the CAD block to display the expanded breakdown for troubleshooting totals and reviewing general area-analysis information.</p></figcaption></figure><figure><a href="${time}" target="_blank" rel="noreferrer"><img src="${time}" alt="Chief Architect Toolbars menu with Time Logging highlighted"></a><figcaption><h3>How to turn on the Time Tracker toolbar</h3><ol><li>Right-click a blank space in the Chief Architect toolbar area.</li><li>Open the <strong>Toolbars</strong> submenu.</li><li>Select <strong>Time Logging</strong> to toggle the Time Tracker toolbar on.</li></ol></figcaption></figure><figure><a href="images/import-plan-layout-settings.png?v=2" target="_blank" rel="noreferrer"><img src="images/import-plan-layout-settings.png?v=2" alt="Chief Architect File menu showing Import Settings From Plan Layout"></a><figcaption><h3>Layout settings and other core feature updates</h3><p>Use the changelog to identify that a core feature changed. For complete operating instructions, examples, and setup details, open the <a href="https://renerabbitt.github.io/ppx18-manual/" target="_blank" rel="noreferrer"><strong>PPX18 User Manual</strong></a>.</p></figcaption></figure></section>`}
function releaseChapter(v,i){const sections=Object.entries(v.changes).map(([name,items],n)=>`<details ${n===0?"open":""}><summary><span>${String(n+1).padStart(2,"0")}</span><div><strong>${esc(name)}</strong><small>${items.length} ${items.length===1?"item":"items"}</small></div></summary><div class="detail-body"><ul class="update-list">${items.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div></details>`).join("");return `<article class="chapter" id="version-${i}"><div class="kicker">RELEASE ${String(i+1).padStart(2,"0")} &middot; SEARCHABLE HTML NOTES</div><h1>${esc(v.version)}</h1><p class="deck">New features, patches, removals, and the exact PPX18 files updated in this version.</p><span class="status-pill ${slug(v.status)}">${esc(v.status)}</span><div class="lesson"><div><div class="accordion-stack">${sections||`<div class="empty">No development notes have been added yet.</div>`}</div>${releaseVisualsFixed(v)}</div>${releaseGuide(v)}</div></article>`}
function setupComparison(){const from=document.querySelector("#compare-from"),to=document.querySelector("#compare-to"),button=document.querySelector("#run-compare"),results=document.querySelector("#compare-results");if(!from||!to||!button||!results)return;const released=versions.map((v,i)=>({v,i})).filter(x=>!slug(x.v.status).includes("unreleased"));const options=released.map(x=>`<option value="${x.i}">${esc(x.v.version)}</option>`).join("");from.innerHTML=options;to.innerHTML=options;if(released.length){from.value=String(released[released.length-1].i);to.value=String(released[0].i)}button.onclick=()=>{const oldIndex=Number(from.value),newIndex=Number(to.value);if(oldIndex===newIndex){results.innerHTML=`<p><strong>No comparison is needed.</strong> You selected the same version twice.</p>`;return}if(oldIndex<newIndex){results.innerHTML=`<p><strong>The destination must be newer than the installed version.</strong> Switch the two selections and try again.</p>`;return}const included=versions.slice(newIndex,oldIndex);const downloads=[...new Set(included.flatMap(v=>v.downloads))];results.innerHTML=`<div class="compare-summary"><strong>${included.length} newer ${included.length===1?"release":"releases"} included</strong><p>To move from ${esc(versions[oldIndex].version)} to ${esc(versions[newIndex].version)}, review every release below and download the named files from the live Dropbox folder.</p><h3>Files updated across these releases</h3><ul class="downloads">${downloads.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div>${included.slice().reverse().map(v=>`<section class="compare-release"><h3>${esc(v.version)}</h3><p><strong>Download:</strong> ${v.downloads.map(esc).join(", ")}</p>${Object.entries(v.changes).map(([name,items])=>`<h4>${esc(name)}</h4><ul>${items.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`).join("")}</section>`).join("")}`}}
function repairPublishedText(){reader.innerHTML=reader.innerHTML.replace(/\u00e2\u20ac\u201d/g,"-");reader.querySelectorAll('a[href="https://rabbitdesign.net"]').forEach(a=>{a.href="https://rabbittdesign.net";a.textContent="rabbittdesign.net"})}
function render(){if(mode==="chapter")reader.innerHTML=active===0?updateChapter():active===1?compareChapter():releaseChapter(versions[active-2],active-2);else reader.innerHTML=updateChapter()+compareChapter()+versions.map(releaseChapter).join("");repairPublishedText();reader.querySelectorAll("[data-update-guide]").forEach(link=>link.addEventListener("click",()=>go(0)));setupComparison();[...nav.children].forEach((b,i)=>b.classList.toggle("active",i===active))}
function go(i){active=Math.max(0,Math.min(versions.length+1,i));rail.classList.remove("open");render();scrollTo({top:0,behavior:"smooth"})}
function parseUnreleased(text){const groups={};let heading="";for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(line.startsWith("## ")){heading=line.slice(3).trim();groups[heading]=groups[heading]||[]}else if(line.startsWith("- ")&&heading)groups[heading].push(line.slice(2).trim())}return groups}
Promise.all([fetch("changelog-data-v4.json",{cache:"no-store"}).then(r=>r.json()),fetch("unreleased-notes.md?v=2",{cache:"no-store"}).then(r=>r.ok?r.text():"").catch(()=>"")]).then(([data,notes])=>{versions=data;const additions=parseUnreleased(notes);if(versions[0])versions[0].changes=Object.fromEntries(Object.entries(additions).filter(([,items])=>items.length));const intro=document.createElement("button");intro.className="install";intro.innerHTML=`<span>00</span><div><strong>How to Update PPX18</strong><small>Find the newest files and follow the update steps</small></div>`;intro.onclick=()=>go(0);nav.append(intro);const compare=document.createElement("button");compare.className="install compare-nav";compare.innerHTML=`<span>01</span><div><strong>Compare PPX18 Versions</strong><small>Combine changes across skipped releases</small></div>`;compare.onclick=()=>go(1);nav.append(compare);versions.forEach((v,i)=>{const b=document.createElement("button");b.className=slug(v.status);b.innerHTML=`<span>${String(i+2).padStart(2,"0")}</span><div><strong>${esc(v.version)}</strong><small>${esc(v.status)}</small><em>${v.downloads.length?`UPDATED: ${v.downloads.map(esc).join(" &middot; ")}`:"NO NOTES YET"}</em></div>`;b.onclick=()=>go(i+2);nav.append(b)});document.querySelector("#count").textContent=versions.length+2;render()});
document.querySelector("#menu").onclick=()=>rail.classList.toggle("open");document.querySelector("#chapter").onclick=()=>{mode="chapter";document.querySelector("#chapter").classList.add("active");document.querySelector("#all").classList.remove("active");render()};document.querySelector("#all").onclick=()=>{mode="all";document.querySelector("#all").classList.add("active");document.querySelector("#chapter").classList.remove("active");render()};document.querySelector("#search").oninput=e=>{const q=e.target.value.toLowerCase();[...nav.children].forEach((b,i)=>b.hidden=q&&!((i===0?updateSearch:i===1?"compare versions skipped releases":JSON.stringify(versions[i-2])).toLowerCase().includes(q)));};
