let versions=[],active=0,mode="chapter";const nav=document.querySelector("#nav"),reader=document.querySelector("#reader"),rail=document.querySelector("#rail");
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const slug=s=>s.toLowerCase().startsWith("unreleased")?"unreleased":s.toLowerCase().startsWith("current")?"current":"previous";
const updateSearch=`updating install download pro plan library toolbar font defaults import settings plan layout z.sys-ProPlan trash CALIBZ beta`;
function steps(items){return `<ol class="steps">${items.map(x=>`<li>${x}</li>`).join("")}</ol>`}
function updateChapter(){return `<article class="chapter update-chapter" id="updating"><div class="kicker">START HERE &middot; INSTALLATION AND MIGRATION</div><h1>Updating the Pro Plan</h1><p class="deck">This chapter explains how to install a new PPX18 release and, when appropriate, bring your preferred settings forward from an older Pro Plan so you do not have to recreate every personal preference.</p><div class="notice"><strong>Start with the release chapter you are installing.</strong><p>Read that version's complete release notes and its "Import from an older plan" panel first. The sidebar tells you which files must be downloaded. The release notes tell you which older settings may be reasonable to import and which settings must remain from the new PPX18 version.</p></div><div class="accordion-stack">
<details open><summary><span>01</span><div><strong>Update the Pro Plan file</strong><small>Open the new release first, then selectively bring forward safe personal preferences</small></div></summary><div class="detail-body"><div class="release-check"><strong>The new Pro Plan is always the destination.</strong><p>Begin with the newly downloaded PPX18 Pro Plan. Do not turn an older customized Pro Plan into the new version by importing everything. Instead, use the new Pro Plan as your working file and selectively copy only preferences that the current release notes say were not changed.</p></div>${steps([
  `Open the release chapter for the PPX18 version you are installing. Read <strong>New Features</strong>, <strong>Patches and Improvements</strong>, <strong>Removed or Replaced</strong>, and the complete <strong>Import from an older plan</strong> panel.`,
  `Download and open the new Pro Plan listed for that version. This new file contains the current PPX18 defaults, macros, labels, custom fields, Saved Plan Views, layer behavior, and other coordinated systems.`,
  `Make a backup copy of the older Pro Plan in which you previously entered your preferred settings. That older file will be the <strong>source</strong>; the newly downloaded Pro Plan is the <strong>destination</strong>.`,
  `In the new destination Pro Plan, choose <strong>File &gt; Import &gt; Import Settings From Plan/Layout</strong>. Select the older customized Pro Plan when Chief Architect asks for the source file.`,
  `Select only the individual setting categories identified as reasonable candidates in that release's migration panel. When importing Saved Plan Views or layer sets, do not select <strong>Replace Originals</strong>.`,
  `After importing, verify the affected defaults and views before beginning production work. If the release notes say PPX18 changed a particular default, label, Project Information field, wall, framing setting, or other system, keep the setting supplied by the new Pro Plan.`
])}<a class="image-link" href="images/import-plan-layout-settings.png?v=2" target="_blank" rel="noreferrer"><img class="menu-shot" src="images/import-plan-layout-settings.png?v=2" alt="Complete Chief Architect File menu showing Import Settings From Plan/Layout"></a><p class="image-note">File &gt; Import &gt; Import Settings From Plan/Layout. Select the image to open the complete original screenshot.</p><h3>Why this selective process matters</h3><p>The purpose is to save time by retaining preferences you already customized without overwriting improvements delivered in the new PPX18 release. An item is not safe merely because Chief Architect allows it to be imported. It is a candidate only when the current release notes show that PPX18 did not change that system.</p><h3>Settings that commonly require extra caution</h3><ul><li>Do not broadly import wall or framing defaults because PPX18 uses version-sensitive layer-based fill styles.</li><li>Do not generally import complete default sets.</li><li>Avoid older window and door labels, room labels, room types, base and full-height cabinet defaults, and door defaults when the release changed those systems.</li><li>Project Information fields may be imported only when the current release did not change how that field reports.</li></ul><h3>Preferred method for customized objects</h3><p>Save the customized object to your user library, place it in the new Pro Plan, run the <strong>Pro Plan Transfer</strong> tool, and then set the updated object as the default. This retains your customization while applying the current custom fields, label macros, and label offsets.</p></div></details>
<details><summary><span>02</span><div><strong>Replace the PPX18 library in X18 Beta</strong><small>Delete the tagged objects, empty Trash, then install the replacement CALIBZ file</small></div></summary><div class="detail-body">${steps([
  `Open the Library Browser and select the tag named <strong>z.sys-ProPlan</strong>.`,
  `Open the filtered-results window, select every item in those results, and right-click the selection.`,
  `Be patient while the context menu opens. In the current X18 beta, this right-click can take up to approximately 40 seconds. The delay is inconsistent and does not appear to correspond to machine performance.`,
  `Choose <strong>Delete</strong>. Deleting the selected library objects can also take a significant and unpredictable amount of time in the beta. Allow Chief Architect to finish.`,
  `Open the Trash library, right-click it, and choose <strong>Empty Trash</strong>. This prevents deleted objects from being detected as duplicates during the next installation.`,
  `After Trash is empty, open the replacement <strong>CALIBZ</strong> file and allow Chief Architect X18 to import the updated library.`
])}<p class="tip"><strong>Important:</strong> Do not install the replacement library until both the tagged objects and the Trash library have been cleared.</p></div></details>
<details><summary><span>03</span><div><strong>Import toolbar configurations</strong><small>Use the same procedure documented in the PPX18 manual</small></div></summary><div class="detail-body">${steps([
  `Right-click a blank area of the toolbars and choose <strong>Customize Toolbars</strong>. You can also open <strong>Tools &gt; Toolbars and Hotkeys &gt; Customize Toolbars</strong>.`,
  `Open the <strong>Configurations</strong> panel and select <strong>Import</strong>.`,
  `Browse to the downloaded Toolbars folder and select every TOOLBAR file in that folder.`,
  `Choose <strong>Replace All</strong> to replace the previous PPX18 configurations.`,
  `If Chief Architect displays <strong>Importing Place Library Object Buttons</strong>, allow the process to finish.`,
  `If a selection dialog appears, choose <strong>Select All New</strong>, then press <strong>Done</strong>.`
])}<p class="tip">Save or back up any personal toolbar configuration first. Importing the Rabbitt Design configuration can overwrite toolbar positions, added buttons, and other customizations.</p></div></details>
<details><summary><span>04</span><div><strong>Verify the complete system</strong><small>Confirm the downloads listed for the release work together</small></div></summary><div class="detail-body"><ul><li>Open several toolbar tools and confirm that they place the expected library objects.</li><li>Confirm the updated Pro Plan, Library, Toolbars, and Font Files listed for the release are installed.</li><li>Check labels, schedules, macros, Saved Plan Views, layouts, and project-information reporting before continuing an active project.</li></ul></div></details></div></article>`}
function explainMigration(item){const text=item.toLowerCase();if(text.includes("floor and ceiling"))return `<strong>Floor and ceiling platform defaults.</strong> If you previously customized platform structure, thickness, materials, or related floor defaults, you may be able to import those specific defaults instead of rebuilding them. Do this only when this release does not list a change to floor or ceiling platforms.`;if(text.includes("saved plan views"))return `<strong>Saved Plan Views.</strong> These may preserve view preferences you already organized. Import them as additional views and leave <em>Replace Originals</em> turned off so the new PPX18 views remain intact.`;if(text.includes("layer sets"))return `<strong>Layer sets.</strong> You may import your personal layer-set variations as new items. Do not replace the layer sets supplied by the new PPX18 release.`;if(text.includes("project-information")||text.includes("project information"))return `<strong>Unchanged Project Information fields.</strong> A field may be brought forward only when this release did not change that field or the way it reports. Compare the release notes before selecting it.`;return `<strong>${esc(item)}.</strong> Treat this as a possible time-saving candidate, not automatic permission to import it. Confirm that the current release did not change the same setting.`}
function explainAvoid(item){const text=item.toLowerCase();if(text.includes("framing")||text.includes("wall"))return `<strong>Framing and wall defaults.</strong> Do not import these from the older plan. PPX18 uses layer-based fill styles and coordinated wall behavior that can be damaged by older defaults.`;if(text.includes("window")||text.includes("door")||text.includes("room")||text.includes("cabinet"))return `<strong>Labels, room systems, doors, windows, and cabinet defaults.</strong> Keep the new PPX18 versions of these items whenever they are listed as changed. For a custom object, use the library plus Pro Plan Transfer method explained in the update chapter.`;if(text.includes("layout")||text.includes("project-information"))return `<strong>Updated layouts and their Project Information fields.</strong> Do not replace the new originals or import an older field that this release changed, because layout labels and reporting may no longer coordinate correctly.`;return `<strong>${esc(item)}.</strong> Keep the setting supplied by the new Pro Plan because this release may depend on its current configuration.`}
function releaseGuide(v){return `<aside class="guide"><section class="card download-card"><h2>Updated in this version</h2><p>Download and install every listed component so the complete PPX18 system remains coordinated.</p><ul class="downloads">${v.downloads.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></section><section class="card migration-card"><h2>Bring preferences forward from an older Pro Plan</h2><p class="migration-intro">This section is for someone who already customized an older Pro Plan and wants to avoid re-entering every preferred setting. The newly downloaded Pro Plan must remain your destination file. Use the older plan only as the source for selected preferences.</p><p><strong>First, read every release-note section on this page.</strong> If this version changed a system, keep the new PPX18 setting instead of importing the older one.</p><h3>Possible time-saving candidates for this release</h3><ul class="migration-list">${v.safe.map(x=>`<li>${explainMigration(x)}</li>`).join("")}</ul><h3>Keep the new PPX18 settings for these items</h3><ul class="migration-list avoid-list">${v.avoid.map(x=>`<li>${explainAvoid(x)}</li>`).join("")}</ul><button class="update-guide-link" type="button" data-update-guide>Open the complete Updating the Pro Plan instructions &rarr;</button></section></aside>`}
function releaseChapter(v,i){const sections=Object.entries(v.changes).map(([name,items],n)=>`<details ${n===0?"open":""}><summary><span>${String(n+1).padStart(2,"0")}</span><div><strong>${esc(name)}</strong><small>${items.length} ${items.length===1?"item":"items"}</small></div></summary><div class="detail-body"><ul class="update-list">${items.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div></details>`).join("");return `<article class="chapter" id="version-${i}"><div class="kicker">RELEASE ${String(i+1).padStart(2,"0")} &middot; SEARCHABLE HTML NOTES</div><h1>${esc(v.version)}</h1><p class="deck">New features, patches, removals, required downloads, and release-specific migration guidance.</p><span class="status-pill ${slug(v.status)}">${esc(v.status)}</span><div class="lesson"><div class="accordion-stack">${sections}</div>${releaseGuide(v)}</div></article>`}
function render(){if(mode==="chapter")reader.innerHTML=active===0?updateChapter():releaseChapter(versions[active-1],active-1);else reader.innerHTML=updateChapter()+versions.map(releaseChapter).join("");reader.querySelectorAll("[data-update-guide]").forEach(link=>link.addEventListener("click",()=>go(0)));[...nav.children].forEach((b,i)=>b.classList.toggle("active",i===active))}
function go(i){active=Math.max(0,Math.min(versions.length,i));rail.classList.remove("open");render();scrollTo({top:0,behavior:"smooth"})}
function parseUnreleased(text){const groups={};let heading="";for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(line.startsWith("## ")){heading=line.slice(3).trim();groups[heading]=groups[heading]||[]}else if(line.startsWith("- ")&&heading)groups[heading].push(line.slice(2).trim())}return groups}
Promise.all([fetch("changelog-data-v2.json",{cache:"no-store"}).then(r=>r.json()),fetch("unreleased-notes.md?v=1",{cache:"no-store"}).then(r=>r.ok?r.text():"").catch(()=>"")]).then(([data,notes])=>{versions=data;const additions=parseUnreleased(notes);if(versions[0])versions[0].changes=Object.fromEntries(Object.entries(additions).filter(([,items])=>items.length));const intro=document.createElement("button");intro.className="install";intro.innerHTML=`<span>00</span><div><strong>Updating the Pro Plan</strong><small>Install, replace, and import safely</small></div>`;intro.onclick=()=>go(0);nav.append(intro);versions.forEach((v,i)=>{const b=document.createElement("button");b.className=slug(v.status);b.innerHTML=`<span>${String(i+1).padStart(2,"0")}</span><div><strong>${esc(v.version)}</strong><small>${esc(v.status)}</small><em>UPDATED: ${v.downloads.map(esc).join(" &middot; ")}</em></div>`;b.onclick=()=>go(i+1);nav.append(b)});document.querySelector("#count").textContent=versions.length+1;render()});
document.querySelector("#menu").onclick=()=>rail.classList.toggle("open");document.querySelector("#chapter").onclick=()=>{mode="chapter";document.querySelector("#chapter").classList.add("active");document.querySelector("#all").classList.remove("active");render()};document.querySelector("#all").onclick=()=>{mode="all";document.querySelector("#all").classList.add("active");document.querySelector("#chapter").classList.remove("active");render()};document.querySelector("#search").oninput=e=>{const q=e.target.value.toLowerCase();[...nav.children].forEach((b,i)=>b.hidden=q&&!(i===0?updateSearch:JSON.stringify(versions[i-1])).toLowerCase().includes(q));};
